### PR TITLE
augment description for mode option in nxos_vlan module

### PR DESCRIPTION
**Pull request by jonasstenling**
Augmented description for mode option in nxos_vlan.

### CODE REVIEW

**Comment by jonasstenling** [comment]
Jason, was there any issue with my updated pull request?

**Comment by WackoRobie** [comment]
I was just digging in to figure out how to adjust VLAN mode. Thank you for doing it!

**Comment by jedelman8** [comment]
Thanks guys.  Will try and get this committed today...looks like there is a conflict, so I'll need to fix it manually.

**Comment by jedelman8** [comment]
Hey @jonasstenling , @WackoRobie  just made me realize something.  This PR only has the docstring being updated...do you want to add `mode` back in? I imagine you do :)

**Comment by jonasstenling** [comment]
Yeah, I don't get it. I created a new branch now in my repo
(add-fabricpath-mode) and when I compare it to the master branch in your
repo the only diff is the augmented docstring. But when I look in the
nxos_vlan file in your repo the code for mode is clearly not there...

**Comment by WackoRobie** [comment]
Are you on devel branch? That is what had me confused. one branch has it and the master does not.

**Comment by jonasstenling** [comment]
The commit is in the devel and the add-fabricpath-mode branches.  I have
not merged it to master.
Den 28 okt 2015 15:43 skrev "WackoRobie" notifications@github.com:

**Comment by jedelman8** [comment]
Should we close those and you can re-open when you want to push again?

**Comment by jonasstenling** [comment]
To be honest I don't know what to do here. The commit that is in both of my branches contains the updated code. Do you want me to merge it to my master branch?

**Comment by jedelman8** [comment]
Do you have a lot of updates in your code?  If not, back yours up, re-fork, and then issue a new PR? In the meantime, I can close this one.  Not sure what's going on either.

**Pull request closed without merging**
