### PR TITLE
augmenting description for nxos_vlan description

### PR DESCRIPTION
**Pull request by jonasstenling**
Same as PR #21.

### CODE REVIEW

**Comment by jedelman8** [comment]
What is this doing for you?  What about `pycsco`?  You update `proposed` but `existing` needs to be updated to, no?

Can you remove `msg` in `results`?  You can just add `vlan_id` to `results` instead.  `state` is already being returned.

**Comment by jonasstenling** [comment]
This is the commit to add mode=ce or mode=fabricpath. Support (partial, anyways) in pycsco was merged with PR https://github.com/jedelman8/pycsco/pull/9.

Regarding your comment on existing I guess you mean that I need to update nxapi.get_vlan() to also include the current mode of the vlan? I will do that and create a new PR for pycsco.

I can remove the msg in results, it's there for our Tower implementation. In Tower msg is shown as the result of the host task so it's an easy way to communicate the result.

**Comment by jonasstenling** [comment]
I think this is ready to be merged together with https://github.com/jedelman8/pycsco/pull/16.

**Comment by jonasstenling** [comment]
A new PR will be raised against the modules-no-pycsco-utils branch.

**Pull request closed without merging**
